### ISSUE TITLE
Class structure for VR_streaming application

### ISSUE THREAD

**Issue by salmanmohebi** [signetlabdei/ns3-802.11ad#17]
I'm writing an application class to simulate the behavior of a gaming server.

As a first step, I'm trying to simulate the paper in [this link](https://dl.acm.org/doi/10.1007/s00530-014-0370-4).

Here the traffic generated based on the following random distributions:
![image](https://user-images.githubusercontent.com/32788253/78979991-3fa0eb00-7b1d-11ea-8c15-8316ea045c97.png)

For some traffics (e.g., upstream traffic), the size and inter-arrival times of the packets, chosen from two different distributions based on a probability. To do this, I've implemented a class name `JointRandomVariable.`

The objects of the `JointRandomVariable` class will be passed to the `UdpStreamingServer` class to generate customized traffic.
Also, `UdpStreamingServerHelper` is the helper class for `UdpStreamingServer.`

My code is not very object-oriented. As you can see in `scratch/evaluate_udp_streaming_server.cc`, every time I need to generate different RandomVariables and pass them to the `JointRandomVariable` class and doesn't encapsulate the details of the class.

Do you have any better structure for these codes?

**Comment by tommyazz** [comment]
Hi Salman,

Does PS Model stand for Packet Size Model? And then, there's an Inter Arrival Time Model?

Why do you need a class JointRandomVariable? 
You could have one class named GamingStreamingServer or something similar (which is basically the current class UdpStreamingServer) and have two distinct models for PS and IAT. These models can be created from the same class according to a set of probabilistic distributions and associated values. So, in principle PS and IAT share the same structure.

Another thing it's not clear to me the content of the tables is some cases. For example, Table 5, Downstream, row 4, how is define the PS model? it means with prob 73.93 % the packet size is to be generated through a uniform random variable [0, 1355], otherwise the packet size is 1356?

**Comment by salmanmohebi** [comment]
Yes, PS stands for packet size.
The idea is to have a base Generator class that receives different types of random variables and generates traffic based on them. (otherwise, I need to write a separate generator for each distribution)
Both of the IAT and PS are chosen from different models (random variables) inside the generator class, and we do not use them separately.

yes it means that (table 5, row 4) in video streams packet size uniformly chosen from [0, 1355] with the probability of 36.06% or [1356] with the probability of 63.94%. also, the interarrival time between packets is 0 with the probability of 57.25% or chosen by Lognormal distribution with a probability of 42.75%.
The `JointRandomVariable` handles this (choosing from different distributions with different probability).

**Comment by mattia-lecci** [comment]
We could talk about this more directly, but looking at this and the code your wrote I would, instead, write separate application classes, like Tommy suggests, called `GameStreamingServer `and `GameStreamingClient`, with purely virtual methods.
Then, extend these classes for the different types of applications, e.g., `CrazytaxyGameStreamingServer`, `CrazyTaxiGameStreamingClient`, etc. each one of them with the list of distributions, basically managing all types of traffics in the same class, but separately for up and downstream. So, `CrazytaxyGameStreamingServer `would have 4 r.v. streams and manage them independently (i don't see any correlation mentioned at a first glance to the paper).
Note that `EmpiricalRandomVariable` could come in handy in some cases, e.g., for uniform+deterministic r.v. or fully deterministic.
Also, be careful with unbounded distributions which could yield IAT/PS <=0

**Comment by tommyazz** [comment]
Ok, I see.

You could create one class say GamingTrafficModel (this is going to be a generic class) where you can model a set of one or more prob distributions each one with an associated probability value as defined in the Tables. For example, if the model in question is just deterministic or just uniform the associated prob is 1. In this way you can build the CDF over the set of distributions. So, for example, an object of this class consists in a list of pairs (prob, probability_distribution). Regarding the probability_distribution, many distributions are already modeled in ns-3 (even a deterministic). Then, you can sample values from this model.
You will have one object of this class for the PS Model and a different one for the IAT model.

Your GamingStreamingServer will produce packet sizes and inter-arrival-times given these two models and just send packets over the socket.
You can use the Helper to create PS and IAT models according to any number of distribution associated with the model and assign them to the GamingStreamingServer. 
In this way you will code two main classes:  GamingTrafficModel and GamingStreamingServer. 

I don't know if it's clear.

**Comment by tommyazz** [comment]
Oh, I just see Mattia's comment. It could be the fastest strategy but it's not scalable and flexible if we want to try many scenarios with different PS and IAT models. 
I don't know our intent about this though, so I'll let you elaborate on this fact.

**Comment by salmanmohebi** [comment]
@tommyazz, actually the `JointRandomVariable` class was an unsuccessful try to do the thing you sais. 
But in my case, this class wasn't a generic one; I guess writing codes in the way you said, make it more clear and maintainable.
Also, I agree with you about @mattia-lecci 's idea.  I think it's better to have separate classes for models and generators. We can discuss this directly.

**Comment by tommyazz** [comment]
Ok, let us know if you need to further discuss this problem.

**Comment by tommyazz** [comment]
@mattia-lecci @MatteoDrago @salmanmohebi 
Should we close this issue?

**Comment by mattia-lecci** [comment]
i would close it with @salmanmohebi's PR

**Comment by mattia-lecci** [comment]
Closed in 504d3fa
